<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_dripicons-exit text-muted</name>
   <tag></tag>
   <elementGuidId>45f86789-11ab-47c5-a990-e77887af950d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='topnav']/div/div/div[2]/ul/li[4]/div/a[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.dripicons-exit.text-muted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dripicons-exit text-muted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav&quot;)/div[@class=&quot;topbar-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;menu-extras topbar-custom&quot;]/ul[@class=&quot;list-inline float-right mb-0&quot;]/li[@class=&quot;list-inline-item dropdown notification-list show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right profile-dropdown show&quot;]/a[@class=&quot;dropdown-item&quot;]/i[@class=&quot;dripicons-exit text-muted&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='topnav']/div/div/div[2]/ul/li[4]/div/a[3]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
   </webElementXpaths>
</WebElementEntity>
